#!/bin/bash

com.bitwarden.desktop
com.discordapp.Discord
net.cozic.joplin_desktop
com.spotify.Client
io.github.flattool.Warehouse
com.github.tchx84.Flatseal
org.onlyoffice.desktopeditors
org.kryogenix.Pick
io.missioncenter.MissionCenter
io.github.prateekmedia.appimagepool