#!/bin/bash

sddm
bspwm
i3lock 
xset 
xautolock
xhost
numlockx #to control the numlock key
sxhkd
# trayer # changed with a new tray in polybar
# polybar

xfce4-panel
xfce4-notifyd
xfce4-xkb-plugin


dmenu
picom
feh
xsetroot #the command that apply cursor theme in bspwmrc
# nitrogen
alsa-utils
alsa-lib
pulseaudio-utils
pavucontrol
polkit-gnome
gnome-keyring
playerctl
xdotool
zsh
flatpak

#themes
adwaita-qt5
adwaita-qt6
arc-theme
materia-kde
materia-gtk-theme
breeze-cursor-theme
papirus-icon-theme
oxygen-cursor-theme
lxappearance
qt5ct
kvantum
# #themes end





seahorse #facilitates the management of GPG keys
langpacks-ar
stow
timeshift
ntpsec
konsole5
dunst

dolphin
ark #archive manager work well with dolphin
flameshot
kwrite
python3-devel gcc #to install pynput
easyeffects
bleachbit
copyq
git
neofetch
vlc
mpv
qbittorrent
thunderbird
ulauncher
gimp
inkscape
krita
shotwell
qalculate-gtk
#kde-partitionmanager
obs-studio
gnome-disk-utility
sysmontask
htop
