#! /bin/sh
bspc rule -r "*" # will reset all rules to configure them again
# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################
export QT_QPA_PLATFORMTHEME=qt5ct
export XCURSOR_SIZE=24
# export XCURSOR_THEME=Simp1e-Mix-Light
export XCURSOR_THEME=Breeze_Snow
# export XCURSOR_PATH=${XCURSOR_PATH}:~/.local/share/icons

# ##############################################################################
# #                                  VARS                                      # 
# ##############################################################################
#export the variables that need to be shown in sxhkdrc
export bspwm_configs=$HOME/.config/bspwm
export configs=$HOME/.config
export scripts=$configs/scripts
picom=$configs/picom/picom.conf
polybar=$configs/polybar/config.ini


# ##############################################################################
# #                                  CONFIGS                                   # 
# ##############################################################################
bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config focus_follows_pointer true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config split_ratio          0.52

bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config single_monocle true

bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5
bsp-layout set tall 6
bsp-layout set tall 7
bsp-layout set tall 8
bsp-layout set tall 9


# ##############################################################################
# #                                  RULES                                     # 
# ##############################################################################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a copyq state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



# ##############################################################################
# #                            INITIAT ENVIRONMENT                             # 
# ##############################################################################
#bspwm
pgrep -x sxhkd > /dev/null || sxhkd -c $bspwm_configs/sxhkdrc &
picom --config $picom &

# pgrep -x polybar > /dev/null || polybar mybar --config=$polybar &

xfce4-panel --disable-wm-check&
feh --bg-fill --randomize $HOME/.wallpapers/* &
playerctld daemon &
#in fedora /usr/libexec/polkit-gnome-authentication-agent-1
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
#preferences
timedatectl set-timezone Africa/Cairo
xsetroot -cursor_name left_ptr #for cursor theme
numlockx on & #to launch with numlock on
setxkbmap -layout 'us,ara' -option 'grp:alt_shift_toggle' &
#apps(Regular Task Apps)
ulauncher --no-window-shadow --hide-window &
dolphin --daemon &
copyq &
flameshot &
#scripts
$scripts/input-vol-blocker.sh &

# ##############################################################################
# #                                  Auto Start                                # 
# ##############################################################################
#for the apps that has window that pop up into my face
discord &



# ##############################################################################
# #                                  THEME                                     # 
# ##############################################################################

bspc config border_width         2
gap=5
bspc config window_gap $gap
bspc config top_padding 20
# bspc config left_padding -$gap
# bspc config right_padding -$gap
# bspc config bottom_padding -$gap

#coloring
bspc config active_border_color '#333333'
bspc config normal_border_color '#333333'
bspc config focused_border_color '#3465a4'
